### ISSUE TITLE
Non-compliant LSP message prevents wider editor support

### ISSUE THREAD

**Issue by gruhn** [dafny-lang/dafny#6172]
### Dafny version

4.10.0

### Command to run and resulting output

I'm sure you don't actually want to reproduce this, but this would be the way:
* Install Helix: https://helix-editor.com/
* In the dafny repository, create a `.helix/languages.toml` with the following content:

```toml
[language-server.dafny-lsp]
command = "/absolute/path/to/dafny/Scripts/dafny"
args = [ "server" ]

[[language]]
name = "dafny"
scope = "source.dafny"
file-types = ["dfy"]
indent = { tab-width = 2, unit = "  " }
language-servers = [ "dafny-lsp" ]
```

* Start Helix in the command line and open a random Dafny file: `hx -vvv --log helix.log Source/DafnyCore/AST/System.dfy`
* Language server exits immediately. Open the newly created log file `helix.log`.  
* Observe the `[ERROR] dafny-lsp` log line

### What happened?

I'm trying to get Dafny running in the [Helix editor](https://helix-editor.com/). But Helix rejects the connection to the language server when it receives these messages: 

https://github.com/dafny-lang/dafny/blob/b118216ca08d48d03c79b42422b17bae817947d6/Source/DafnyLanguageServer/DafnyLanguageServer.cs#L107-L109

If I comment out these two lines and compile Dafny locally, the language server seems to be compatible with Helix. I think the problem is that the version number passed via `params` is just a string, while the LSP standard specifies that it should be an array or object: 

```typescript
interface NotificationMessage extends Message {
	/**
	 * The method to be invoked.
	 */
	method: string;

	/**
	 * The notification's params.
	 */
	params?: Array<any> | object;
}
```

Maybe VSCode is more lenient. 

I would try to provide a fix myself but I have zero C# experience. Not sure how to turn this into an object/array. And if that then breaks the VSCode client.

### What type of operating system are you experiencing the problem on?

Linux
